//--------------------------------------------------------------------------
// This file is generated by the SeRoNet Tooling. The SeRoNet Tooling is 
// developed by the SeRoNet Project consortium: 
// http://www.seronet-projekt.de
//
// The ROS Mixed-Port Component is developed by:
// Service Robotics Research Center of Ulm University of Applied Sciences
// Fraunhofer Institute for Manufacturing Engineering and Automation IPA
//
// This code-generator uses infrastructure of the SmartMDSD Toolchain on
// which the SeRoNet Tooling is based on.
//
// CAUTION: 
// This software is a preview for the purpose of technology demonstration. 
// It is experimental and comes with no support. Use at your own risk.
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentUUVSonarRosPortExtension.hh"

// statically create a global PlainOpcUaComponentUUVSonarExtension instance
static ComponentUUVSonarRosPortExtension ros_port_extension;

ComponentUUVSonarRosPortExtension::ComponentUUVSonarRosPortExtension()
:	ComponentUUVSonarExtension("ComponentUUVSonarRosPortExtension")
{
	nh = 0;
	callbacksPtr = 0;
}

ComponentUUVSonarRosPortExtension::~ComponentUUVSonarRosPortExtension()
{  }

void ComponentUUVSonarRosPortExtension::loadParameters(const SmartACE::SmartIniParameter &parameter)
{  }

void ComponentUUVSonarRosPortExtension::initialize(ComponentUUVSonar *component, int argc, char* argv[])
{
	ros::init(argc, argv, "ComponentUUVSonar", ros::init_options::NoSigintHandler);
	nh = new ros::NodeHandle();
	
	callbacksPtr = new ComponentUUVSonarRosPortCallbacks();
	
	component->rosPorts = this;
	
	_sonar = nh->subscribe("/rexrov/sonar", 10, &ComponentUUVSonarRosPortCallbacks::_sonar_cb, callbacksPtr);
}

int ComponentUUVSonarRosPortExtension::onStartup()
{
	return startExtensionThread();
}

int ComponentUUVSonarRosPortExtension::extensionExecution()
{
	ros::spin();
	return 0;
}

int ComponentUUVSonarRosPortExtension::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	ros::shutdown();
	return stopExtensionThread(timeoutTime);
}

void ComponentUUVSonarRosPortExtension::destroy()
{
	delete nh;
	delete callbacksPtr;
}
