//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "ManipulatorCommandTask.hh"
#include "ComponentUUVManipulator.hh"

#include <iostream>

ManipulatorCommandTask::ManipulatorCommandTask(SmartACE::SmartComponent *comp) 
:	ManipulatorCommandTaskCore(comp)
{
	std::cout << "constructor ManipulatorCommandTask\n";
}
ManipulatorCommandTask::~ManipulatorCommandTask() 
{
	std::cout << "destructor ManipulatorCommandTask\n";
}


int ManipulatorCommandTask::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	return 0;
}
int ManipulatorCommandTask::on_execute()
{
	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
	// to get the incoming data, use this methods:
	Smart::StatusCode status;

	CommBasicObjects::CommNavigationVelocity navvel;

	// get velocity command and publish
	if (COMP->navvel != NULL)
	{
		navvel = COMP->navvel->getNavigationVelocity();
		geometry_msgs::Twist cmd;
		cmd.linear.x = navvel.get_vX()/1000.0;
		cmd.linear.y = navvel.get_vY()/1000.0;
		cmd.linear.z = 0;
		cmd.angular.x = 0;
		cmd.angular.y = 0;
		cmd.angular.z = navvel.get_omega();

		COMP->rosPorts->_cmd_vel_publish_ros_msg(cmd);
	}

	std::cout << "Commanded Velocity: " << navvel << std::endl;

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int ManipulatorCommandTask::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
