//--------------------------------------------------------------------------
// This file is generated by the SeRoNet Tooling. The SeRoNet Tooling is 
// developed by the SeRoNet Project consortium: 
// http://www.seronet-projekt.de
//
// The ROS Mixed-Port Component is developed by:
// Service Robotics Research Center of Ulm University of Applied Sciences
// Fraunhofer Institute for Manufacturing Engineering and Automation IPA
//
// This code-generator uses infrastructure of the SmartMDSD Toolchain on
// which the SeRoNet Tooling is based on.
//
// CAUTION: 
// This software is a preview for the purpose of technology demonstration. 
// It is experimental and comes with no support. Use at your own risk.
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentUUVSimulatorRosPortCallbacks.hh"

// include component's main class
#include "ComponentUUVSimulator.hh"

ComponentUUVSimulatorRosPortCallbacks::ComponentUUVSimulatorRosPortCallbacks() {  }

ComponentUUVSimulatorRosPortCallbacks::~ComponentUUVSimulatorRosPortCallbacks() {  }

void ComponentUUVSimulatorRosPortCallbacks::_pose_cb (const nav_msgs::Odometry::ConstPtr &msg)
{
	// for implementing this method, you can use the "COMP->" macro to access the component's class members
	COMP->baseStateTask->update_pose(msg);
	
}


