//--------------------------------------------------------------------------
// This file is generated by the SeRoNet Tooling. The SeRoNet Tooling is 
// developed by the SeRoNet Project consortium: 
// http://www.seronet-projekt.de
//
// The ROS Mixed-Port Component is developed by:
// Service Robotics Research Center of Ulm University of Applied Sciences
// Fraunhofer Institute for Manufacturing Engineering and Automation IPA
//
// This code-generator uses infrastructure of the SmartMDSD Toolchain on
// which the SeRoNet Tooling is based on.
//
// CAUTION: 
// This software is a preview for the purpose of technology demonstration. 
// It is experimental and comes with no support. Use at your own risk.
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentUUVManipulatorRosPortExtension.hh"

// statically create a global PlainOpcUaComponentUUVManipulatorExtension instance
static ComponentUUVManipulatorRosPortExtension ros_port_extension;

ComponentUUVManipulatorRosPortExtension::ComponentUUVManipulatorRosPortExtension()
:	ComponentUUVManipulatorExtension("ComponentUUVManipulatorRosPortExtension")
{
	nh = 0;
	callbacksPtr = 0;
}

ComponentUUVManipulatorRosPortExtension::~ComponentUUVManipulatorRosPortExtension()
{  }

void ComponentUUVManipulatorRosPortExtension::loadParameters(const SmartACE::SmartIniParameter &parameter)
{  }

void ComponentUUVManipulatorRosPortExtension::initialize(ComponentUUVManipulator *component, int argc, char* argv[])
{
	ros::init(argc, argv, "ComponentUUVManipulator", ros::init_options::NoSigintHandler);
	nh = new ros::NodeHandle();
	
	callbacksPtr = new ComponentUUVManipulatorRosPortCallbacks();
	
	component->rosPorts = this;
	
	_cmd_vel = nh->advertise<geometry_msgs::Twist>("/rexrov/oberon4/cmd_vel", 10);
}

int ComponentUUVManipulatorRosPortExtension::onStartup()
{
	return startExtensionThread();
}

int ComponentUUVManipulatorRosPortExtension::extensionExecution()
{
	ros::spin();
	return 0;
}

int ComponentUUVManipulatorRosPortExtension::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	ros::shutdown();
	return stopExtensionThread(timeoutTime);
}

void ComponentUUVManipulatorRosPortExtension::destroy()
{
	delete nh;
	delete callbacksPtr;
}
