//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BASESTATETASK_HH
#define _BASESTATETASK_HH

#include "BaseStateTaskCore.hh"

#include <mutex>
#include <nav_msgs/Odometry.h>

class BaseStateTask  : public BaseStateTaskCore
{
private:
	std::mutex m_mtx;
	CommBasicObjects::CommBasePose m_commBasePose;
public:
	BaseStateTask(SmartACE::SmartComponent *comp);
	virtual ~BaseStateTask();
	
	void update_pose(const nav_msgs::Odometry::ConstPtr &msg);

	CommBasicObjects::CommBasePose getBasePose();

	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
