//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SmartUUVSimServerAcePortFactory.hh"

// create a static instance of the default AcePortFactory
static SmartUUVSimServerAcePortFactory acePortFactory;

SmartUUVSimServerAcePortFactory::SmartUUVSimServerAcePortFactory()
{  
	componentImpl = 0;
	SmartUUVSimServer::instance()->addPortFactory("ACE_SmartSoft", this);
}

SmartUUVSimServerAcePortFactory::~SmartUUVSimServerAcePortFactory()
{  }

void SmartUUVSimServerAcePortFactory::initialize(SmartUUVSimServer *component, int argc, char* argv[])
{
	if(component->connections.component.defaultScheduler != "DEFAULT") {
		ACE_Sched_Params sched_params(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(component->connections.component.defaultScheduler == "FIFO") {
			sched_params.policy(ACE_SCHED_FIFO);
			sched_params.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(component->connections.component.defaultScheduler == "RR") {
			sched_params.policy(ACE_SCHED_RR);
			sched_params.priority(ACE_THR_PRI_RR_MIN);
		}
		// create new instance of the SmartSoft component with customized scheuling parameters 
		componentImpl = new SmartUUVSimServerImpl(component->connections.component.name, argc, argv, sched_params);
	} else {
		// create new instance of the SmartSoft component
		componentImpl = new SmartUUVSimServerImpl(component->connections.component.name, argc, argv);
	}
}

int SmartUUVSimServerAcePortFactory::onStartup()
{
	return componentImpl->startComponentInfrastructure();
}


Smart::IQueryServerPattern<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState> * SmartUUVSimServerAcePortFactory::createBaseSatateQueryAnsw(const std::string &serviceName)
{
	return new SmartACE::QueryServer<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState>(componentImpl, serviceName);
}

Smart::IPushServerPattern<CommBasicObjects::CommBaseState> * SmartUUVSimServerAcePortFactory::createBaseStateServiceOut(const std::string &serviceName)
{
	return new SmartACE::PushServer<CommBasicObjects::CommBaseState>(componentImpl, serviceName);
}

Smart::IPushServerPattern<CommBasicObjects::CommMobileLaserScan> * SmartUUVSimServerAcePortFactory::createLaserServiceOut(const std::string &serviceName)
{
	return new SmartACE::PushServer<CommBasicObjects::CommMobileLaserScan>(componentImpl, serviceName);
}

Smart::ISendServerPattern<CommBasicObjects::CommBasePositionUpdate> * SmartUUVSimServerAcePortFactory::createLocalizationUpdateServiceIn(const std::string &serviceName)
{
	return new SmartACE::SendServer<CommBasicObjects::CommBasePositionUpdate>(componentImpl, serviceName);
}

Smart::ISendServerPattern<CommBasicObjects::CommNavigationVelocity> * SmartUUVSimServerAcePortFactory::createNavVelServiceIn(const std::string &serviceName)
{
	return new SmartACE::SendServer<CommBasicObjects::CommNavigationVelocity>(componentImpl, serviceName);
}


SmartACE::SmartComponent* SmartUUVSimServerAcePortFactory::getComponentImpl()
{
	return componentImpl;
}

int SmartUUVSimServerAcePortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	componentImpl->stopComponentInfrastructure(timeoutTime);
	return 0;
}

void SmartUUVSimServerAcePortFactory::destroy()
{
	// clean-up component's internally used resources (internally used communication middleware) 
	componentImpl->cleanUpComponentResources();
	delete componentImpl;
}
